import { UITextKey } from './labelKeys';
export { UITextKey } from './labelKeys';

export const UI_TEXT: Record<UITextKey, string> = {
  [UITextKey.CommonSave]: 'Lưu',
  [UITextKey.CommonCancel]: 'Hủy',
  [UITextKey.CommonClose]: 'Đóng',
  [UITextKey.CommonDelete]: 'Xóa',
  [UITextKey.CommonEdit]: 'Sửa',
  [UITextKey.CommonCreate]: 'Tạo mới',
  [UITextKey.CommonSearch]: 'Tìm kiếm',
  [UITextKey.CommonRefresh]: 'Tải lại',
  [UITextKey.CommonRetry]: 'Thử lại',
  [UITextKey.CommonLoading]: 'Đang tải...',
  [UITextKey.CommonNoData]: 'Không có dữ liệu',
  [UITextKey.CommonConfirm]: 'Xác nhận',
  [UITextKey.CommonBack]: 'Quay lại',

  [UITextKey.AuthLoginTitle]: 'Đăng nhập',
  [UITextKey.AuthUsernameLabel]: 'Tên đăng nhập',
  [UITextKey.AuthPasswordLabel]: 'Mật khẩu',
  [UITextKey.AuthLoginButton]: 'Đăng nhập',

  [UITextKey.UploadSelectFile]: 'Chọn tệp',
  [UITextKey.UploadDownload]: 'Tải xuống',
  [UITextKey.UploadVerify]: 'Kiểm tra tải lên',

  [UITextKey.TextSua]: 'Sửa',
  [UITextKey.TextDatLaiMatKhau]: 'Đặt lại mật khẩu',
  [UITextKey.TextNgungDung]: 'Ngừng dùng',
  [UITextKey.TextMoTaKhongBatBuoc]: 'Mô tả (không bắt buộc)',
  [UITextKey.TextXoaFile]: 'Xóa tệp',
  [UITextKey.TextTuThang]: 'Từ tháng',
  [UITextKey.TextChonThangBatDau]: 'Chọn tháng bắt đầu',
  [UITextKey.TextDenThang]: 'Đến tháng',
  [UITextKey.TextChonThangKetThuc]: 'Chọn tháng kết thúc',
  [UITextKey.TextTuNam]: 'Từ năm',
  [UITextKey.TextTuQuy]: 'Từ quý',
  [UITextKey.TextDenNam]: 'Đến năm',
  [UITextKey.TextDenQuy]: 'Đến quý',
  [UITextKey.TextChonNamBatDau]: 'Chọn năm bắt đầu',
  [UITextKey.TextChonNamKetThuc]: 'Chọn năm kết thúc',
  [UITextKey.TextTimDonVi]: 'Tìm đơn vị...',
  [UITextKey.TextChonCaCayDonViNay]: 'Chọn cả cây đơn vị này',
  [UITextKey.TextXemDonViCapDuoi]: 'Xem đơn vị cấp dưới',
  [UITextKey.TextTickODongDonViDeChonCaCay]: 'Đánh dấu ở dòng đơn vị để chọn cả cây đơn vị. Bấm vào dòng để mở danh sách người dùng của đơn vị đó.',
  [UITextKey.TextLoai]: 'Loại',
  [UITextKey.TextTimUsernameHoTen]: 'Tìm tên đăng nhập / họ tên...',
  [UITextKey.TextThuGonCapNay]: 'Thu gọn cấp này',
  [UITextKey.TextVU]: 'Ảo',
  [UITextKey.TextCoTheChonTungDonViHoacDungChon]: 'Có thể chọn từng đơn vị hoặc dùng “Chọn tất cả” ở từng cột để lấy toàn bộ các đơn vị đang hiển thị trong cột đó.',
  [UITextKey.TextChonNgay]: 'Chọn ngày',
  [UITextKey.TextChuaThietLap]: 'Chưa thiết lập',
  [UITextKey.TextChuaThietLap2]: 'Chưa thiết lập',
  [UITextKey.TextChonKhoangNgay]: 'Chọn khoảng ngày',
  [UITextKey.TextDonVi]: 'Đơn vị',
  [UITextKey.TextHienThiCongViecDuocGiao]: 'Hiển thị công việc được giao',
  [UITextKey.TextHienThiTongHopBaoCao]: 'Hiển thị tổng hợp báo cáo',
  [UITextKey.TextCoDanhGiaThuCong]: 'Có đánh giá thủ công',
  [UITextKey.TextCongViecDuocGiaoActive]: 'Công việc đang hiệu lực',
  [UITextKey.TextDaDanhGia]: 'Đã đánh giá',
  [UITextKey.TextHanHoanThanh]: 'Hạn hoàn thành',
  [UITextKey.TextCapNhatGanNhat]: 'Cập nhật gần nhất',
  [UITextKey.TextPhanBoTienDoCongViecDuocGiao]: 'Phân bố tiến độ công việc được giao',
  [UITextKey.TextTongBaoCao]: 'Tổng báo cáo',
  [UITextKey.TextDangChoXuLy]: 'Đang chờ xử lý',
  [UITextKey.TextDaDuyet]: 'Đã duyệt',
  [UITextKey.TextQuaHan]: 'Quá hạn',
  [UITextKey.TextCoCauTrangThaiBaoCao]: 'Cơ cấu trạng thái báo cáo',
  [UITextKey.TextCoReportChamMuon]: 'Có báo cáo kết quả chậm',
  [UITextKey.TextCoDanhGiaTay]: 'Có đánh giá thủ công',
  [UITextKey.TextDangTaiNhanh]: 'Đang tải nhánh...',
  [UITextKey.TextTimUser]: 'Tìm người dùng',
  [UITextKey.TextUsernameHoacHoTen]: 'Tên đăng nhập hoặc họ tên',
  [UITextKey.TextTuNgay]: 'Từ ngày',
  [UITextKey.TextDenNgay]: 'Đến ngày',
  [UITextKey.TextMauTrangThai]: 'Màu trạng thái',
  [UITextKey.TextTheoDonViNguoi]: 'Theo đơn vị / người',
  [UITextKey.TextClickVaoTungMauDeMoDanhSachDon]: 'Bấm vào từng màu để mở danh sách đơn vị tương ứng.',
  [UITextKey.TextTheoTongReport]: 'Theo tổng số báo cáo',
  [UITextKey.TextDrilldownTheoReportKyBaoCaoTrongToanBo]: 'Xem chi tiết báo cáo/kỳ báo cáo trong toàn bộ nhánh này.',
  [UITextKey.TextTimNhanh]: 'Tìm nhanh',
  [UITextKey.TextAssignmentNguoiDungDonViKyBaoCao]: 'Công việc, người dùng, đơn vị, kỳ báo cáo...',
  [UITextKey.TextTenUserUsernameDonViKy]: 'Họ tên, tên đăng nhập, đơn vị, kỳ...',
  [UITextKey.TextChonKhoangNgay2]: 'Chọn khoảng ngày',
  [UITextKey.TextDonVi2]: 'Đơn vị',
  [UITextKey.Text0AssignmentDangHienThi]: '0 công việc đang hiển thị',
  [UITextKey.Text1NodeDaNap]: '1 mục đã tải',
  [UITextKey.TextNhapMaHoacTenWork]: 'Nhập mã hoặc tên công việc...',
  [UITextKey.TextHuy]: 'Hủy',
  [UITextKey.TextTimTheoMaHoacTenWork]: 'Tìm theo mã hoặc tên công việc',
  [UITextKey.TextNoiDungTongHop]: 'Nội dung tổng hợp',
  [UITextKey.TextAssignmentBaoCao]: 'Công việc cần báo cáo',
  [UITextKey.TextChonAssignmentDeLocBaoCao]: 'Chọn công việc để lọc báo cáo',
  [UITextKey.TextMaDaiDien]: 'Mã đại diện',
  [UITextKey.TextTenBoDanhGia]: 'Tên bộ đánh giá',
  [UITextKey.TextPhamViDonVi]: 'Phạm vi đơn vị',
  [UITextKey.TextViDuPV01DeTrongNeuMuonDungChung]: 'Ví dụ: PV01. Để trống nếu muốn dùng chung.',
  [UITextKey.TextTrangThai]: 'Trạng thái',
  [UITextKey.TextThuTu]: 'Thứ tự',
  [UITextKey.TextMa]: 'Mã',
  [UITextKey.TextTenHienThi]: 'Tên hiển thị',
  [UITextKey.TextTimTheoMaHoacTenBo]: 'Tìm theo mã hoặc tên bộ',
  [UITextKey.TextBoMaDanhGia]: 'Bộ mã đánh giá',
  [UITextKey.TextChonBoMaDungChoDanhGiaThuCong]: 'Chọn bộ mã dùng cho đánh giá thủ công ở phần giao việc',
  [UITextKey.TextXemChiTiet]: 'Xem chi tiết',
  [UITextKey.TextTaiLai]: 'Tải lại',
  [UITextKey.TextChonBoMaDeXemNhanh]: 'Chọn bộ mã để xem nhanh',
  [UITextKey.TextChonBoMaDanhGia]: 'Chọn bộ mã đánh giá',
  [UITextKey.TextTenBoMa]: 'Tên bộ mã',
  [UITextKey.TextViDuPV01]: 'Ví dụ: PV01',
  [UITextKey.TextMaCon]: 'Mã con',
  [UITextKey.TextNhanHienThi]: 'Nhãn hiển thị',
  [UITextKey.TextTen]: 'Tên',
  [UITextKey.TextXem]: 'Xem',
  [UITextKey.TextTaoDynamicForm]: 'Tạo biểu mẫu động',
  [UITextKey.TextXoa]: 'Xóa',
  [UITextKey.TextCopyMa]: 'Sao chép mã',
  [UITextKey.TextMaBang]: 'Mã bảng',
  [UITextKey.TextTenBang]: 'Tên bảng',
  [UITextKey.TextHeaderSoHang1200]: 'Phần tiêu đề: số hàng (1..200)',
  [UITextKey.TextHeaderSoCot1200]: 'Phần tiêu đề: số cột (1..200)',
  [UITextKey.TextDataTongSoDong1200]: 'Phần dữ liệu: tổng số dòng (1..200)',
  [UITextKey.TextHeaderSoDong1200]: 'Phần tiêu đề: số dòng (1..200)',
  [UITextKey.TextDataTongSoCot1200]: 'Phần dữ liệu: tổng số cột (1..200)',
  [UITextKey.TextTopRows1200]: 'Số dòng phía trên (1..200)',
  [UITextKey.TextTopCols1200]: 'Số cột phía trên (1..200)',
  [UITextKey.TextLeftRows1200]: 'Số dòng bên trái (1..200)',
  [UITextKey.TextLeftCols1200]: 'Số cột bên trái (1..200)',
  [UITextKey.TextTimNhan]: 'Tìm nhãn',
  [UITextKey.TextTrangThai2]: 'Trạng thái',
  [UITextKey.TextInactive]: 'Ngừng dùng',
  [UITextKey.TextSuaNhan]: 'Sửa nhãn',
  [UITextKey.TextXoaNhan]: 'Xóa nhãn',
  [UITextKey.TextTaoNhanMoi]: 'Tạo nhãn mới',
  [UITextKey.TextMaNhan]: 'Mã nhãn',
  [UITextKey.TextTenNhan]: 'Tên nhãn',
  [UITextKey.TextNhom]: 'Nhóm',
  [UITextKey.TextMau]: 'Màu',
  [UITextKey.TextPhamVi]: 'Phạm vi',
  [UITextKey.TextScopeId]: 'Mã phạm vi',
  [UITextKey.TextMoTa]: 'Mô tả',
  [UITextKey.TextActive]: 'Đang dùng',
  [UITextKey.TextThongBao]: 'Thông báo',
  [UITextKey.TextXoaTatCa]: 'Xóa tất cả',
  [UITextKey.TextChonDonViVaDanhDauNguoiDungHoac]: 'Chọn đơn vị và đánh dấu người dùng hoặc tìm kiếm theo tên tài khoản',
  [UITextKey.TextTimTheoTenTaiKhoan]: 'Tìm theo tên tài khoản',
  [UITextKey.TextTimKiemTrongDonViDangChon]: 'Tìm kiếm trong đơn vị đang chọn',
  [UITextKey.TextTimKiemNhanhTheoTenTaiKhoan]: 'Tìm kiếm nhanh theo tên tài khoản',
  [UITextKey.TextMoChiTiet]: 'Mở chi tiết',
  [UITextKey.TextChuaCo]: 'Chưa có',
  [UITextKey.TextTimMaTenBieuMau]: 'Tìm mã / tên biểu mẫu',
  [UITextKey.TextBieuMau]: 'Biểu mẫu',
  [UITextKey.TextNguonLayBaoCao]: 'Nguồn lấy báo cáo',
  [UITextKey.TextScope]: 'Phạm vi',
  [UITextKey.TextKieuTongHop]: 'Kiểu tổng hợp',
  [UITextKey.TextMetricFilter]: 'Lọc chỉ số',
  [UITextKey.TextDonViTongHop]: 'Đơn vị tổng hợp',
  [UITextKey.TextPhamViKy]: 'Phạm vi kỳ',
  [UITextKey.TextNgayKy]: 'Ngày/kỳ',
  [UITextKey.TextTuNgay2]: 'Từ ngày',
  [UITextKey.TextDenNgay2]: 'Đến ngày',
  [UITextKey.TextLuyKeDenNgayKy]: 'Lũy kế đến ngày/kỳ',
  [UITextKey.TextChonBieuMauDaThietKe]: 'Chọn biểu mẫu đã thiết kế',
  [UITextKey.TextChonBieuMau]: 'Chọn biểu mẫu',
  [UITextKey.TextXemTruocBieuMau]: 'Xem trước biểu mẫu',
  [UITextKey.TextXoaChon]: 'Xóa chọn',
  [UITextKey.TextTimTheoMaTen]: 'Tìm theo mã / tên',
  [UITextKey.TextChonDynamicForm]: 'Chọn biểu mẫu động',
  [UITextKey.TextChonFormDaPublish]: 'Chọn biểu mẫu đã công bố',
  [UITextKey.TextXoaChon2]: 'Xóa chọn',
  [UITextKey.TextTimTheoMaTen2]: 'Tìm theo mã / tên',
  [UITextKey.TextLoaiKy]: 'Loại kỳ',
  [UITextKey.TextNgayBatDauApDung]: 'Ngày bắt đầu áp dụng',
  [UITextKey.TextNhanhCongViec]: 'Nhánh công việc',
  [UITextKey.TextDinhKyMotLan]: 'Định kỳ / Một lần',
  [UITextKey.TextHanNop]: 'Hạn nộp',
  [UITextKey.TextBaoCaoChuDong]: 'Báo cáo chủ động',
  [UITextKey.TextDonViDuocGiao]: 'Đơn vị được giao',
  [UITextKey.TextLanhDaoChiHuyTheoDoi]: 'Lãnh đạo, chỉ huy theo dõi',
  [UITextKey.TextChonLanhDaoChiHuyTheoDoi]: 'Chọn lãnh đạo, chỉ huy theo dõi',
  [UITextKey.TextMoTa2]: 'Mô tả',
  [UITextKey.TextAssignment]: 'Công việc',
  [UITextKey.TextBoTieuChi]: 'Bộ tiêu chí',
  [UITextKey.TextDanhGiaHienTai]: 'Đánh giá hiện tại',
  [UITextKey.TextKetQuaDanhGia]: 'Kết quả đánh giá',
  [UITextKey.TextNhanXet]: 'Nhận xét',
  [UITextKey.TextLyDo]: 'Lý do',
  [UITextKey.TextTimTheoBieuMauNguoiDuocGiao]: 'Tìm theo biểu mẫu / người được giao',
  [UITextKey.TextLoaiGiao]: 'Loại giao',
  [UITextKey.TextHieuLuc]: 'Hiệu lực',
  [UITextKey.TextTienDo]: 'Tiến độ',
  [UITextKey.TextDaCoDuLieu]: 'Đã có dữ liệu',
  [UITextKey.TextKhoaBieuMau]: 'Khóa biểu mẫu',
  [UITextKey.TextChuaLuuThayDoi]: 'Chưa lưu thay đổi',
  [UITextKey.TextKieuTinhToanTongHop]: 'Kiểu tính toán / tổng hợp',
  [UITextKey.TextCanBoDauMoi]: 'Cán bộ đầu mối',
  [UITextKey.TextChonCanBoDauMoi]: 'Chọn cán bộ đầu mối',
  [UITextKey.TextTongHop]: 'Tổng hợp',
  [UITextKey.TextGiaoViec]: 'Giao việc',
  [UITextKey.TextChiTietAssignment]: 'Chi tiết công việc',
  [UITextKey.TextTimNhanh2]: 'Tìm nhanh',
  [UITextKey.TextTaiKhoan]: 'Tài khoản',
  [UITextKey.TextNgayKyBaoCao]: 'Ngày kỳ báo cáo',
  [UITextKey.TextXemDanhSachReview]: 'Xem danh sách cần duyệt',
  [UITextKey.TextDuyetBaoCao]: 'Duyệt báo cáo kết quả',
  [UITextKey.TextTraLaiBaoCao]: 'Trả lại để sửa',
  [UITextKey.TextThuHoiDuyet]: 'Thu hồi duyệt',
  [UITextKey.TextAnBaoCao]: 'Ẩn báo cáo',
  [UITextKey.TextKichHoatLai]: 'Kích hoạt lại',
  [UITextKey.TextSoDong]: 'Số dòng',
  [UITextKey.TextTuKhoaMaTen]: 'Từ khóa (mã/tên)',
  [UITextKey.TextLanhDaoChiDao]: 'Lãnh đạo chỉ đạo',
  [UITextKey.TextUuTien]: 'Ưu tiên',
  [UITextKey.TextTaiXuong]: 'Tải xuống',
  [UITextKey.TextTuNgayDenNgay]: 'Từ ngày – đến ngày',
  [UITextKey.TextHan]: 'Hạn',
  [UITextKey.TextGhiChu]: 'Ghi chú',
  [UITextKey.TextSua2]: 'Sửa',
  [UITextKey.TextXoaMem]: 'Xóa mềm',
  [UITextKey.TextTimMaTenHoacLoaiDonVi]: 'Tìm mã, tên hoặc loại đơn vị',
  [UITextKey.TextXoaChucVu]: 'Xóa chức vụ',
  [UITextKey.TextMaChucVu]: 'Mã chức vụ',
  [UITextKey.TextTenChucVu]: 'Tên chức vụ',
  [UITextKey.TextOrder]: 'Thứ tự',
  [UITextKey.TextRank]: 'Xếp hạng',
  [UITextKey.TextTenDayDu]: 'Tên đầy đủ',
  [UITextKey.TextTenRutGon]: 'Tên rút gọn',
  [UITextKey.TextKyHieu]: 'Ký hiệu',
  [UITextKey.TextLoaiDonVi]: 'Loại đơn vị',
  [UITextKey.TextUnitAoGomNhomKhongTaoUserTrucTiep]: 'Đơn vị ảo để gom nhóm, không tạo người dùng trực tiếp',
  [UITextKey.TextTimDonVi2]: 'Tìm đơn vị',
  [UITextKey.TextSuaDonVi]: 'Sửa đơn vị',
  [UITextKey.TextNgungDungDonVi]: 'Ngừng dùng đơn vị',
  [UITextKey.TextUnitAo]: 'Đơn vị ảo',
  [UITextKey.TextXoaMem2]: 'Xóa mềm',
  [UITextKey.TextTimMaHoacTenLoaiDonVi]: 'Tìm mã hoặc tên loại đơn vị',
  [UITextKey.TextXoaLoaiDonVi]: 'Xóa loại đơn vị',
  [UITextKey.TextMaLoai]: 'Mã loại',
  [UITextKey.TextTenLoaiDonVi]: 'Tên loại đơn vị',
  [UITextKey.TextMaxUserUnit]: 'Số người tối đa/đơn vị',
  [UITextKey.TextMatKhauMoi]: 'Mật khẩu mới',
  [UITextKey.TextToiThieu6KyTu]: 'Tối thiểu 6 ký tự',
  [UITextKey.TextUsername]: 'Tên đăng nhập',
  [UITextKey.TextPassword]: 'Mật khẩu',
  [UITextKey.TextHoTen]: 'Họ tên',
  [UITextKey.TextChucVu]: 'Chức vụ',
  [UITextKey.TextTimUsernameFullName]: 'Tìm tên đăng nhập / họ tên',
  [UITextKey.TextNgungDungUser]: 'Ngừng dùng người dùng',
  [UITextKey.TextBack]: 'Quay lại',
  [UITextKey.TextMa2]: 'Mã',
  [UITextKey.TextTenForm]: 'Tên biểu mẫu',
  [UITextKey.TextFormLabels]: 'Nhãn biểu mẫu',
  [UITextKey.TextChonNhanForm]: 'Chọn nhãn biểu mẫu',
  [UITextKey.TextMoveUp]: 'Di chuyển lên',
  [UITextKey.TextMoveDown]: 'Di chuyển xuống',
  [UITextKey.TextRemoveBlock]: 'Xóa phần bảng',
  [UITextKey.TextBlockLabels]: 'Nhãn phần bảng',
  [UITextKey.TextChonNhanBlock]: 'Chọn nhãn cho phần bảng',
  [UITextKey.TextAllowedRowLabels]: 'Nhãn dòng được chọn',
  [UITextKey.TextChonNhanDong]: 'Chọn nhãn dòng',
  [UITextKey.TextDanhSachNhanChoNguoiNhapBaoCaoChon]: 'Danh sách nhãn để người nhập báo cáo chọn cho từng dòng.',
  [UITextKey.TextLabelColumns]: 'Cột chứa nhãn dòng',
  [UITextKey.TextVD13]: 'VD: 1, 3',
  [UITextKey.TextNhapSoThuTuCotExcelDungLamMetadata]: 'Nhập số thứ tự cột Excel dùng làm nhãn; các cột này sẽ không tính vào dữ liệu báo cáo.',
  [UITextKey.TextStatisticColumns]: 'Cột cần thống kê',
  [UITextKey.TextVD24]: 'VD: 2, 4',
  [UITextKey.TextStatisticColumnLabels]: 'Mã nhãn cho cột thống kê',
  [UITextKey.TextVD2Revenue4Cost]: 'VD: 2:doanh_thu, 4:chi_phi',
  [UITextKey.TextChiGanLabelChoCotDaNamTrongStatistic]: 'Chỉ gán nhãn thống kê cho cột đã chọn để thống kê. Mỗi nhãn chỉ gán cho một trường dữ liệu hoặc một cột.',
  [UITextKey.TextChonNhan]: 'Chọn nhãn',
  [UITextKey.TextAddSection]: 'Thêm phần',
  [UITextKey.TextSectionTitle]: 'Tiêu đề phần',
  [UITextKey.TextSectionDescription]: 'Mô tả phần',
  [UITextKey.TextSectionLabels]: 'Nhãn phần',
  [UITextKey.TextChonNhanSection]: 'Chọn nhãn cho phần',
  [UITextKey.TextRequired]: 'Bắt buộc',
  [UITextKey.TextStat]: 'Thống kê',
  [UITextKey.TextUp]: 'Lên',
  [UITextKey.TextDown]: 'Xuống',
  [UITextKey.TextDelete]: 'Xóa',
  [UITextKey.TextLabel]: 'Nhãn',
  [UITextKey.TextKey]: 'Mã',
  [UITextKey.TextFieldLabels]: 'Nhãn trường dữ liệu thống kê',
  [UITextKey.TextChonNhanField]: 'Chọn nhãn cho trường dữ liệu',
  [UITextKey.TextChiFieldDaBatStatisticMoiDuocGanLabel]: 'Chỉ trường dữ liệu đã bật thống kê mới được gán nhãn thống kê. Mỗi nhãn chỉ gán cho một trường dữ liệu hoặc một cột.',
  [UITextKey.TextCols]: 'Số cột',
  [UITextKey.TextHeight]: 'Chiều cao',
  [UITextKey.TextStatistic]: 'Thống kê',
  [UITextKey.TextDetail]: 'Chi tiết',
  [UITextKey.TextTree]: 'Cây',
  [UITextKey.TextOptions]: 'Tùy chọn',
  [UITextKey.TextTen2]: 'Tên',
  [UITextKey.TextKhoangNgayTao]: 'Khoảng ngày tạo',
  [UITextKey.TextPublish]: 'Công bố',
  [UITextKey.TextClone]: 'Sao chép',
  [UITextKey.TextXoa2]: 'Xóa',
  [UITextKey.TextCopy]: 'Sao chép',
  [UITextKey.TextThongKe]: 'Thống kê',
  [UITextKey.TextSourceType]: 'Loại nguồn',
  [UITextKey.TextSourceIdOptional]: 'Mã nguồn (không bắt buộc)',
  [UITextKey.TextEmailTenDangNhap]: 'Email / Tên đăng nhập',
  [UITextKey.TextMatKhau]: 'Mật khẩu',
  [UITextKey.Text3DonViCoGiaTriCaoNhat]: '3 đơn vị có giá trị cao nhất',
  [UITextKey.TextXoaBangBieu]: 'Xóa bảng biểu',
  [UITextKey.TextTimNhan2]: 'Tìm nhãn',
  [UITextKey.TextNhom2]: 'Nhóm',
  [UITextKey.TextMaNhan2]: 'Mã nhãn',
  [UITextKey.TextChiDungChuThuongSoDauHoac]: 'Chỉ dùng chữ thường, số, dấu -, _ hoặc .',
  [UITextKey.TextTenNhan2]: 'Tên nhãn',
  [UITextKey.TextMau2]: 'Màu',
  [UITextKey.TextPhamVi2]: 'Phạm vi',
  [UITextKey.TextXoaNhan2]: 'Xóa nhãn',
  [UITextKey.TextLichSuThaoTac]: 'Lịch sử thao tác',
  [UITextKey.TextJobRun]: 'Lượt chạy',
  [UITextKey.TextTimKiem]: 'Tìm kiếm',
  [UITextKey.TextThaoTac]: 'Thao tác',
  [UITextKey.TextUnitID]: 'Mã đơn vị',
  [UITextKey.TextUserID]: 'Mã người dùng',
  [UITextKey.TextStatusResult]: 'Trạng thái / kết quả',
  [UITextKey.TextActionOperation]: 'Thao tác',
  [UITextKey.TextWorkID]: 'Mã công việc',
  [UITextKey.TextAssignmentID]: 'Mã công việc',
  [UITextKey.TextTruncated]: 'Đã rút gọn',
  [UITextKey.TextTrangThaiHienTai]: 'Trạng thái hiện tại',
  [UITextKey.TextLyDoNoiDungBaoCao]: 'Lý do / nội dung báo cáo',
  [UITextKey.TextKhoKhanVuongMac]: 'Khó khăn, vướng mắc',
  [UITextKey.TextPhuongAnGiaiQuyetDeXuat]: 'Phương án giải quyết / đề xuất',
  [UITextKey.TextLyDoTreHan]: 'Lý do trễ hạn',
  [UITextKey.TextLyDoThuHoi]: 'Lý do thu hồi',
  [UITextKey.TextThuocTinhChung]: 'Thuộc tính chung',
  [UITextKey.TextBaoCao]: 'Báo cáo',
  [UITextKey.TextGiamSatNhiemVu]: 'Giám sát nhiệm vụ',
  [UITextKey.TextGiamSatChiTieu]: 'Giám sát chỉ tiêu',

  [UITextKey.TextDong]: 'Đóng',
  [UITextKey.TextTatCa]: 'Tất cả',
  [UITextKey.TextTaiKhoanDonVi]: 'Tài khoản đơn vị',
  [UITextKey.TextNguoiDungThuong]: 'Người dùng thường',
  [UITextKey.TextTatCa2]: '-- Tất cả --',
  [UITextKey.TextChonChucVu]: '-- Chọn chức vụ --',
  [UITextKey.TextDangDung]: 'Đang dùng',
  [UITextKey.TextDanhSachMaDiKem]: 'Danh sách mã đi kèm',
  [UITextKey.TextBoMaDanhGiaThuCong]: 'Bộ mã đánh giá thủ công',
  [UITextKey.TextChuaCoBoMaDanhGiaChonThemMoi]: 'Chưa có bộ mã đánh giá. Chọn Thêm mới để tạo.',
  [UITextKey.TextThemBoMaDanhGia]: 'Thêm bộ mã đánh giá',
  [UITextKey.TextCacMaConDiKem]: 'Các mã con đi kèm',
  [UITextKey.TextKhongTaiDuocBieuMauDeXemTruoc]: 'Không tải được biểu mẫu để xem trước.',
  [UITextKey.TextBangNgang]: 'Bảng ngang',
  [UITextKey.TextBangDoc]: 'Bảng dọc',
  [UITextKey.TextBangMaTran]: 'Bảng ma trận',
  [UITextKey.TextKetQuaLuu]: 'Kết quả lưu',
  [UITextKey.TextHopLeDaSanSangLuuCauHinhHeader]: 'Hợp lệ. Đã sẵn sàng lưu cấu hình phần tiêu đề.',
  [UITextKey.TextKhongHopLeSuaCacLoiSau]: 'Không hợp lệ. Sửa các lỗi sau:',
  [UITextKey.TextQuanLyNhanDynamicForm]: 'Quản lý nhãn biểu mẫu động',
  [UITextKey.TextTatCa3]: 'Tất cả',
  [UITextKey.TextGlobal]: 'Toàn hệ thống',
  [UITextKey.TextLevel]: 'Theo cấp',
  [UITextKey.TextUnit]: 'Đơn vị',
  [UITextKey.TextChuaLam]: 'Chưa làm',
  [UITextKey.TextDaNop]: 'Đã nộp',
  [UITextKey.TextBiTuChoi]: 'Bị từ chối',
  [UITextKey.TextChiBaoCaoDaDuyet]: 'Chỉ báo cáo đã duyệt',
  [UITextKey.TextDaDuyetDaNop]: 'Đã duyệt + đã nộp',
  [UITextKey.TextDirectChildren]: 'Nhánh trực tiếp',
  [UITextKey.TextFullSubtree]: 'Toàn bộ nhánh',
  [UITextKey.TextCongVaoBieuMau]: 'Cộng vào biểu mẫu',
  [UITextKey.TextGhepNgangTheoNguoi]: 'Ghép ngang theo người',
  [UITextKey.TextGhepDocTheoNguoi]: 'Nối dòng theo người/đơn vị',
  [UITextKey.TextMotNgayKy]: 'Một ngày/kỳ',
  [UITextKey.TextTuNgayDenNgay2]: 'Từ ngày đến ngày',
  [UITextKey.TextToanBoKy]: 'Toàn bộ kỳ',
  [UITextKey.TextChonBieuMauDong]: 'Chọn biểu mẫu động',
  [UITextKey.TextHangNgay]: 'Hàng ngày',
  [UITextKey.TextTuan]: 'Tuần',
  [UITextKey.TextThang]: 'Tháng',
  [UITextKey.TextQuy]: 'Quý',
  [UITextKey.TextNuaNam]: 'Nửa năm',
  [UITextKey.TextGiaoCongViec]: 'Giao công việc',
  [UITextKey.TextChonNhanhCongViecGoc]: 'Chọn nhánh công việc gốc',
  [UITextKey.TextGiaoMotLan]: 'Giao một lần',
  [UITextKey.TextDinhKyBaoCao]: 'Định kỳ báo cáo',
  [UITextKey.TextDanhGiaAssignment]: 'Đánh giá công việc',
  [UITextKey.TextKhongTaiDuocBoTieuChiDanhGia]: 'Không tải được bộ tiêu chí đánh giá.',
  [UITextKey.TextKhongTaiDuocLichSuDanhGia]: 'Không tải được lịch sử đánh giá.',
  [UITextKey.TextChuaCoLichSuDanhGiaNao]: 'Chưa có lịch sử đánh giá nào.',
  [UITextKey.TextMotLan]: 'Một lần',
  [UITextKey.TextDinhKy]: 'Định kỳ',
  [UITextKey.TextDangHieuLuc]: 'Đang hiệu lực',
  [UITextKey.TextNgungHieuLuc]: 'Ngừng hiệu lực',
  [UITextKey.TextChuaBatDau]: 'Chưa bắt đầu',
  [UITextKey.TextDangThucHien]: 'Đang thực hiện',
  [UITextKey.TextHoanThanh]: 'Hoàn thành',
  [UITextKey.TextCoRuiRo]: 'Có rủi ro',
  [UITextKey.TextMATRIX]: 'Bảng ma trận',
  [UITextKey.TextUNITROWCOL]: 'Đơn vị theo dòng/cột',
  [UITextKey.TextKhongTaiDuocDanhSachAssignment]: 'Không tải được danh sách công việc.',
  [UITextKey.TextKhongCoAssignmentPhuHopVoiBoLocHien]: 'Không có công việc phù hợp với bộ lọc hiện tại.',
  [UITextKey.TextTatCaDonViDaGiao]: 'Tất cả đơn vị đã giao',
  [UITextKey.TextTatCaTaiKhoanDaGiao]: 'Tất cả tài khoản đã giao',
  [UITextKey.TextDangTaiDuLieuReview]: 'Đang tải dữ liệu cần duyệt...',
  [UITextKey.TextDanhSachKyCanDanhGia]: 'Danh sách kỳ cần đánh giá',
  [UITextKey.TextTatCaDonVi]: 'Tất cả đơn vị',
  [UITextKey.TextTatCaTaiKhoan]: 'Tất cả tài khoản',
  [UITextKey.TextDangTaiDanhSachKy]: 'Đang tải danh sách kỳ...',
  [UITextKey.TextXemBaoCao]: 'Xem báo cáo',
  [UITextKey.TextDangTaiLen]: 'Đang tải lên…',
  [UITextKey.TextDangSua]: 'Đang sửa',
  [UITextKey.TextDonViCapTren]: 'Đơn vị cấp trên',
  [UITextKey.TextChonLoaiDonVi]: '-- Chọn loại đơn vị --',
  [UITextKey.TextHuy2]: 'Huỷ',
  [UITextKey.TextThieuUnitIdUnitCodeTrongMeKhongTheTaiCay]: 'Thiếu thông tin đơn vị trong tài khoản hiện tại. Không thể tải cây đơn vị.',
  [UITextKey.TextDangTaiCayDonVi]: 'Đang tải cây đơn vị...',
  [UITextKey.TextKhongTaiDuocCayDonVi]: 'Không tải được cây đơn vị.',
  [UITextKey.TextKhongCoDonViPhuHop]: 'Không có đơn vị phù hợp.',
  [UITextKey.TextDangChon]: 'Đang chọn',
  [UITextKey.TextChuaChonDonVi]: 'Chưa chọn đơn vị.',
  [UITextKey.TextSYSTEMADMINMoiDuocThemSuaNgungDungHoac]: 'Chỉ tài khoản ADMIN hoặc quản trị hệ thống mới được thêm, sửa, ngừng dùng hoặc nhập đơn vị.',
  [UITextKey.TextKetQuaKiemTraImportDonVi]: 'Kết quả kiểm tra tệp nhập đơn vị',
  [UITextKey.TextDaXoa]: 'Đã xóa',
  [UITextKey.TextResetMatKhau]: 'Đặt lại mật khẩu',
  [UITextKey.TextHuy3]: 'Hủy',
  [UITextKey.TextKetQuaKiemTraImportUser]: 'Kết quả kiểm tra tệp nhập người dùng',
  [UITextKey.TextTableBlocks]: 'Các bảng dữ liệu',
  [UITextKey.TextExcelBlock]: 'Bảng Excel động',
  [UITextKey.TextSections]: 'Các phần',
  [UITextKey.TextFields]: 'Trường dữ liệu',
  [UITextKey.TextNoFields]: 'Chưa có trường dữ liệu',
  [UITextKey.TextNoFieldSelected]: 'Chưa chọn trường dữ liệu',
  [UITextKey.TextField]: 'Trường dữ liệu',
  [UITextKey.TextDraft]: 'Bản nháp',
  [UITextKey.TextPublished]: 'Đã công bố',
  [UITextKey.TextMoiTrangThai]: 'Mọi trạng thái',
  [UITextKey.TextUploadError]: 'Lỗi tải lên',
  [UITextKey.TextThongTinNguoiDung]: 'Thông tin người dùng',
  [UITextKey.TextDangXuat]: 'Đăng xuất',
  [UITextKey.TextMissingId]: 'Thiếu mã dữ liệu',
  [UITextKey.TextLoadingForm]: 'Đang tải biểu mẫu...',
  [UITextKey.TextCannotLoadForm]: 'Không tải được biểu mẫu',
  [UITextKey.TextQuanLyBoMaDanhGiaDungChung]: 'Quản lý bộ mã đánh giá dùng chung.',
  [UITextKey.TextDangTaiDanhSachBoDanhGia]: 'Đang tải danh sách bộ đánh giá...',
  [UITextKey.TextKhongCoBoDanhGiaPhuHopVoiBo]: 'Không có bộ đánh giá phù hợp với bộ lọc hiện tại.',
  [UITextKey.TextThieuId]: 'Thiếu mã dữ liệu',
  [UITextKey.TextDangTaiBangBieu]: 'Đang tải bảng biểu...',
  [UITextKey.TextKhongTaiDuocBangBieu]: 'Không tải được bảng biểu',
  [UITextKey.TextToanHeThong]: 'Toàn hệ thống',
  [UITextKey.TextType]: 'Loại',
  [UITextKey.TextBucket]: 'Nhóm dữ liệu',
  [UITextKey.TextPeriod]: 'Kỳ báo cáo',
  [UITextKey.TextValue]: 'Giá trị',
  [UITextKey.TextCount]: 'Số lượng',
  [UITextKey.TextReports]: 'Báo cáo',
  [UITextKey.TextText]: 'Nội dung',
  [UITextKey.TextKhANgTaIAACTemplateDynamicExcel]: 'Không tải được biểu mẫu Excel động.',
  [UITextKey.TextOutputRow]: 'Dòng kết quả',
  [UITextKey.TextGroup]: 'Nhóm',
  [UITextKey.TextMetricKey]: 'Mã chỉ số',
  [UITextKey.TextRow]: 'Dòng',
  [UITextKey.TextColumn]: 'Cột',
  [UITextKey.TextSum]: 'Tổng',
  [UITextKey.TextMin]: 'Nhỏ nhất',
  [UITextKey.TextMax]: 'Lớn nhất',
  [UITextKey.TextAverage]: 'Trung bình',
  [UITextKey.TextTextConcat]: 'Ghép nội dung',
  [UITextKey.TextAssignee]: 'Người thực hiện',
  [UITextKey.TextChars]: 'Ký tự',
  [UITextKey.TextLichSuThaoTacBaoCao]: 'Lịch sử thao tác báo cáo',
  [UITextKey.TextDangTaiLog]: 'Đang tải nhật ký...',
  [UITextKey.TextKhongTaiDuocLogBaoCao]: 'Không tải được nhật ký báo cáo.',
  [UITextKey.TextChuaCoLogNao]: 'Chưa có nhật ký nào.',
  [UITextKey.TextThieuReportId]: 'Thiếu mã báo cáo.',
  [UITextKey.TextDangTaiBaoCao]: 'Đang tải báo cáo...',
  [UITextKey.TextDangTaiTruongBoSung]: 'Đang tải trường bổ sung...',
  [UITextKey.TextThuHoiBaoCaoDaNop]: 'Thu hồi báo cáo đã nộp',
  [UITextKey.TextKhongTaiDuocChiTietBieuMauBaoCao]: 'Không tải được chi tiết biểu mẫu báo cáo.',
  [UITextKey.TextKhongCoKyBaoCaoPhuHopVoiBo]: 'Không có kỳ báo cáo phù hợp với bộ lọc hiện tại.',
  [UITextKey.TextThieuWorkIdDeTaiDanhSachBaoCao]: 'Thiếu mã công việc để tải danh sách báo cáo.',
  [UITextKey.TextKhongTaiDuocDanhSachBaoCao]: 'Không tải được danh sách báo cáo.',
  [UITextKey.TextKhongCoNhomBieuMauBaoCaoPhuHop]: 'Không có nhóm biểu mẫu báo cáo phù hợp.',
  [UITextKey.TextThieuId2]: 'Thiếu mã dữ liệu.',
};

export function uiText(key: UITextKey): string {
  return UI_TEXT[key];
}
